name: Envoys
main: bajan\Envoys\Main
version: 0.0.2
api: [3.0.0-ALPHA10, 3.0.0-ALPHA11]
author: BajanVlogs
description: Spawn envoys in the warzone for you players to collect items

commands:
 setenvoy:
  description: Set an envoy
